@startuml
autonumber "<b>0'.'"
box "Participant A" #LightPink
Participant "Participant A\nClient" as ParticipantA
Participant "Participant A\nDID Document" as DID
Participant "Participant A\nIdentity Hub" as IDHUB
end box
box "Participant B" #LightGreen
Participant "Participant B\nAPI" as B
end box
box "Authority"
Participant "Authority\nDID Document" as Auth
end box
ParticipantA -> B ++: Request:\n - DID JWS
activate ParticipantA
group authorize request
  B -> DID: Get DID Document (contains Identity Hub URL)
  B -> B: Verify JWS using public key
  B -> IDHUB: Get Verifiable Credentials
  B -> Auth: Get DID document (contains public key)
  B -> B: Verify VC using public key
  B -> B: Apply access policy
end
return Response
deactivate ParticipantA

@enduml