resources:
  - base/namespace.yaml
  - base/vault.yaml
  - base/gateway.yaml
  - base/gateway-class.yaml
  - base/postgres.yaml
  - base/keycloak.yaml
  - application/issuerservice-config.yaml
  - application/issuerservice.yaml
  - application/issuerservice-seed-job.yaml