#
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#

---
name: "Execute E2E Tests"
on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * *" # once a day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_run:
    workflows: [ "Draft Release" ]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Run-E2E-Tests:
    runs-on: ubuntu-latest
    steps:

      - name: "Setup Helm"
        uses: azure/setup-helm@v5

      - name: "Setup Kubectl"
        uses: azure/setup-kubectl@v5
      - uses: actions/checkout@v6
      - uses: eclipse-edc/.github/.github/actions/setup-build@main

      - name: "Build runtime images"
        working-directory: ./
        run: |
          ./gradlew dockerize 

      - name: "Create k8s Kind Cluster"
        uses: helm/kind-action@v1.14.0
        with:
          cluster_name: dcp-demo

      - name: "Load runtime images into KinD"
        run: | 
          kind load docker-image -n dcp-demo \
          ghcr.io/eclipse-edc/minimumviabledataspace/controlplane:latest \
          ghcr.io/eclipse-edc/minimumviabledataspace/dataplane:latest \
          ghcr.io/eclipse-edc/minimumviabledataspace/identity-hub:latest \
          ghcr.io/eclipse-edc/minimumviabledataspace/issuerservice:latest

      - name: "Update image pull policy"
        run: |-
          grep -rl "imagePullPolicy: Always" k8s | xargs sed -i "s/imagePullPolicy: Always/imagePullPolicy: Never/g"

      - name: "Install Traefik Gateway controller"
        run: |-
          helm repo add traefik https://traefik.github.io/charts
          helm repo update
          helm upgrade --install --namespace traefik traefik traefik/traefik --create-namespace -f values.yaml

          # Wait for traefik to be ready
          kubectl rollout status deployment/traefik -n traefik --timeout=120s

          # forward port 80 -> 8080
          kubectl -n traefik port-forward svc/traefik 8080:80 &

          # install Gateway API CRDs
          kubectl apply --server-side --force-conflicts -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.1/experimental-install.yaml

          sleep 5 # to be safe`

      - name: "Deploy MVD"
        run: |-
          kubectl apply -k k8s/ 

      - name: "Wait for MVD to be ready"
        run: |-
          kubectl wait -A \
            --selector=type=edc-job \
            --for=condition=complete job --all \
            --timeout=300s || kubectl get pods -A


      - name: "Run E2E Test"
        run: |-
          ./gradlew -DincludeTags="EndToEndTest" test -DverboseTest=true

      - name: "Destroy the KinD cluster"
        run: >-
          kind delete cluster -n dcp-demo

  Secrets-Presence:
    name: "Check for required credentials"
    runs-on: ubuntu-latest
    outputs:
      HAS_WEBHOOK: ${{ steps.secrets-presence.outputs.HAS_WEBHOOK }}
    steps:
      - name: Check whether secrets exist
        id: secrets-presence
        run: |
          [ ! -z "${{ secrets.DISCORD_GITHUB_CI_WEBHOOK }}" ] && echo "HAS_WEBHOOK=true" >> $GITHUB_OUTPUT
          exit 0

  Post-To-Discord:
    needs: [ Run-E2E-Tests, Secrets-Presence ]
    if: "needs.Secrets-Presence.outputs.HAS_WEBHOOK && always() && github.event_name == 'schedule'"
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        name: "Post discord webhook"
        with:
          webhook: ${{ secrets.DISCORD_GITHUB_CI_WEBHOOK }}
          # if the publishing is skipped, that means the preceding test run failed
          status: ${{ needs.Run-E2E-Tests.result == 'skipped' && 'Failure' || needs.Run-E2E-Tests.result }}
          title: "Nightly MVD E2E-Test"
          description: Nightly E2E test run against the latest artefacts"
          username: GitHub Actions